name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run all tests
      run: cargo test --all --verbose

  run-solutions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run all solutions
      run: cargo run --release -- --skip-output --loops 10 2>/dev/null
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}

  run-benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run all benchmarks
      run: cargo bench
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
